botvin_lifeskills/urls.py
from django.conf.urls import patterns, url

from botvin_lifeskills import views

urlpatterns = patterns('',

	url(r'^section/(?P<section>\D+)/(?P<school_level>\D+)$', views.botvinSection, name='botvinsurvey'),

    url(r'^section/botvinVote/$', views.botvinSectionVote, name="botvinSectionVote"),

    url(r'^section/results/$', views.results, name="results"),
    
    url(r'^excel', views.temp, name="temp"),
    
    url(r'^download/(?P<school_level>\D+)', views.excel, name="excel"),
  
    url(r'^index', views.index, name="index"),

    url(r'^thankyou/', views.end, name="end"),


)

events/urls.py
#django urls
from django.conf.urls import patterns, url

from events import views


urlpatterns = patterns('',

	url(r'^eventsToAndroid/$', views.events_to_android, name='events_to_android'),

)

sunstreet/urls.py
from django.conf.urls import patterns, include, url
import forms_builder.forms.urls

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'sunstreet.views.home', name='home'),
    # url(r'^sunstreet/', include('sunstreet.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^demographics/', include('demographics.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^botvin/', include('botvin_lifeskills.urls', namespace="botvin_lifeskills")),
    url(r'^topnews/', include('top_news.urls', namespace='top_news')),
    url(r'^forms/', include(forms_builder.forms.urls)),
    url(r'^events/', include('events.urls', namespace="events")),

)

sunstreet/templates/botvin/base.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
		    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    		<!-- Bootstrap -->
    		<link href="{% static 'css/bootstrap-fluid-adj.css' %}" rel="stylesheet">
    		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
    		<link href="{% static 'css/bootstrap-responsive.css' %}" rel="stylesheet">
        <style type="text/css">
            .multiple-checkbox ul { /* Used to hide <li> elements in multiple checkbox forms */
              padding-left: 0px;
              list-style: none;
            }


        </style>

    </head>
    <body style="    background: -webkit-linear-gradient(left, #FFEA00, #F28500); /* For Safari 5.1 to 6.0 */
    background: -o-linear-gradient(right, #FFEA00, #F28500); /* For Opera 11.1 to 12.0 */
    background: -moz-linear-gradient(right, #FFEA00, #F28500); /* For Firefox 3.6 to 15 */
    background: linear-gradient(to right, #FFEA00, #F28500); /* Standard syntax (must be last) */">
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  			<!-- Brand and toggle get grouped for better mobile display -->
  			<div class="navbar-header">

  			</div>
  			
		</nav>

<main class="bs-masthead" id="content" role="main">
  <div class="container">
    {% block body_block %}
    {% endblock %}
  </div>
</main>

		<script src="{% static 'js/jquery-2.1.1.min.js' %}"></script>
    	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	</body>
</html>
		

sunstreet/templates/botvin/displayquestions.html
{% extends "botvin/base.html" %}
{% load static %}
{% block body_block %}
	<head>
		<title>{{school_level}} Botvin Lifeskills Survey {{section}}</title>
		<script src="{% static 'js/jquery-2.1.1.min.js' %}"></script>
		<script src="{% static 'js/jquery.validate.js' %}"></script>


        <style>
            label.error {
                color: red;
                text-decoration: underline;
                font-weight: bold;
            }
        </style>
	</head>
	<body class="body">
		<header class = "mainHead">
			<h1 style="text-align:center; margin-bottom: 25px;"> Botvin Lifeskills Section {{section}}</h1>
		</header>

		{% if error_message %}
			<h3><strong>{{ error_message }}</strong></h3>
			<a href="{% url 'botvin_lifeskills:botvinsurvey' section school_level %}"><h4>GO BACK</h4></a>
		{% endif %}

        {% ifequal section "B" %}<p> Read each statement below and indicate whether you think each is True or False by filling in the appropriate circle. </p>{% endifequal %}

        {% if school_level == "ES" %}{% if section == "C" %}<p> Mark the circle to show if you agree or disagree with each of the statements below. </p>{% endif %}
        {% elif section == "C" %}<p> Please fill in the circle to show how much you agree or disagree with each statement.</p>{% endif %}

        {% if school_level == "ES" %}{% if section == "D" %}<p> Mark he circle for each statement to show how often you do the following things</p>{% endif %}
        {% elif section == "D" %}<p> Please fill in each circle to show how you would handle the following situations. </p>{% endif %}

        <form action="{% url 'botvin_lifeskills:botvinSectionVote'  %}" method="post" id="radio_group" name="radio_group">

            <input type="hidden" value="{{school_level}}" name="school_level">
            <input type="hidden" value="{{section}}" name="section">
		{% csrf_token %}

		{% for question in questions %}
			<div style="margin-bottom: 2cm;">
                {% if school_level == "ES" %}{% if section == "D" %}{% if forloop.counter == 7 %}<p> Mark the word for each statement to show how likely you would be to do the following things.</p>{%endif%}{%endif%}
                {% elif section == "D" %}{% if forloop.counter == 1 %}<p> How likely would you be to: </p>{%endif%}
                {% if forloop.counter == 6 %}<p> How likely would you do the following things: </p>{%endif%}
                {% if forloop.counter == 9 %}<p> When you feel anxious you: </p>{%endif%}
                {% if forloop.counter == 11 %}<p> In general: </p>{%endif%}{%endif%}


            <p style="font-size:x-large; font-weight: bold;">{{question.question_number}}. {{question}}</p>
		    {% for choice in question.answer_set.all %}

               		<label style="font-size: large;">
			    	<input type="radio" name=choice{{question.question_number}} id="choice{{ forloop.counter }}" value="{{ choice.id }}" required/>
			    	{{ choice.choices }}
			    	</label><br />
				
		    {% endfor %}
			</div>
        {% endfor %}

		{% if not error_message %}
			<div class="buttonHolder">
				<input type="submit" value="Submit" />
			</div>
		{% endif %}
			
		</form>
			<script>
				$(document).ready(function () {
				$("#radio_group").validate();
				}(jQuery));

			</script>

	</body>
{% endblock %}

sunstreet/templates/botvin/end.html
{% extends "botvin/base.html" %}
{% load static %}
{% block body_block %}
<script type="text/javascript">
function closeWindow() {
setTimeout(function() {
window.close();
}, 10000);
}

window.onload = closeWindow();
</script>
	
<body>
	<h1>Thank you. Your response has been recorded.</h1>
	<p> This window will close in 10 seconds</p>	
</body>
{% endblock %}

sunstreet/templates/botvin/index.html
{% extends "botvin/base.html" %}
{% block body_block %}
	<title>Botvin Questionnaires</title>
	<head>
		<link rel="stylesheet" type="text/css" media="all" href="/static/botvin_lifeskills/index.css" />
        <script type="text/javascript" src='/static/js/jquery-2.1.1.min.js'></script>
        <script type="text/javascript" src='/static/js/index.js'></script>
	</head>

	<body>

	<header class="mainHead">
		<h1 style="text-align: center;">Botvin</h1>
	</header>

	
    <div class = "choose_school"> <center><strong>Choose the school you attend:</strong>
        <select name="School_Choice" id="item1" form="schoolform">
            <option value=""></option>
            {% for school in schools %}
                <option value="{{school}}">{{school}}</option>
            {% endfor %}
        </select>
        </center>
    </div>


    <form action="section/A/" method="post" id="schoolform" name="school_select_form">
	    
                {% csrf_token %}
                <input type="image" id = "ES" src = "/static/img/elementary.png" value = "ES" style="width:75%;margin-top: 5%;margin-left:13%;border-radius:40px;-webkit-border-radius: 40px;-moz-border-radius: 40px;">
                <input type="image" id = "MS" src="/static/img/middle.png" value = "MS" style="width:75%;margin-top: 5%;margin-left: 13%;border-radius:40px;-webkit-border-radius: 40px;-moz-border-radius: 40px;">
                <input type="image" id = "HS" src="/static/img/highschool.png" value = "HS" style="width:75%;margin-top: 5%;margin-left: 13%;border-radius:40px;-webkit-border-radius: 40px;-moz-border-radius: 40px;">
    </form>





	</body>

{% endblock %}

	

sunstreet/templates/botvin/temp.html
<html>

	<h1>Download excel sheets of data here</h1>
	<ul>
		<li><a href="/botvin/download/ES">Elementary School</a></li>
		<li><a href="/botvin/download/MS">Middle School</a></li>
		<li><a href="/botvin/download/HS">High School</a></li>
	</ul>
</html>